dbms_app/urls.py
from django.contrib import admin
from django.urls import path
from dbms_app import views
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'dbms_app'

urlpatterns = [
    path('home/',views.home,name='home'),
    path('cust-register/',views.cust_register, name="cust_register"),
    path('emp-register/',views.emp_register, name="emp_register"),
    path('supp-register/',views.supp_register, name="supp_register"),
    path('login/',LoginView.as_view(template_name='dbms_app/login.html'),name='login'),
    path('logout/',LogoutView.as_view(template_name='dbms_app/logout.html'),name='logout'),
    path('buy-porsche',views.buy_porsche,name='buy_porsche'),
    path('buy-lamborghini',views.buy_lamborghini,name='buy_lamborghini'),    
    path('buy-harley',views.buy_harley,name='buy_harley'),  
    path('buy-royal',views.buy_royal,name='buy_royal'),  
    path('buy-benz',views.buy_benz,name='buy_benz'),
    path('success',views.success,name='success'),   
    path('profile',views.profile,name='profile'), 
    path('emp-profile',views.emp_profile,name='emp_profile'),
    path('cust-profile',views.cust_profile,name='cust_profile'),
    path('supp-profile',views.supp_profile,name='supp_profile')
]

dbms_backend/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dbms_app.urls',namespace='dbms_app')),
]

dbms_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from .models import Profile,Customer,Product,Employee,Supplier

class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username',
            'password1',
            'password2'
        )

    def save(self,commit=True):
        user = super(RegistrationForm,self).save(commit=False)


        if commit:
            user.save()

            return user

class CustomerProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = (
            'name',
            'address',

        )

    def save(self,commit=True):
        profile = super(CustomerProfileForm,self).save(commit=False)
        profile.name = self.cleaned_data['name']
        profile.address = self.cleaned_data['address']
        id = User.objects.latest('date_joined')
        profile.user = id
        profile.user_type = 'C'
        
        if commit:
            profile.save()
            cust = Customer(id = Employee.objects.all().count()+1, name = profile.name , address = profile.address)
            cust.save()

            return profile

class EmployeeProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = (
            'name',
            'address',

        )

    def save(self,commit=True):
        profile = super(EmployeeProfileForm,self).save(commit=False)
        profile.name = self.cleaned_data['name']
        profile.address = self.cleaned_data['address']
        id = User.objects.latest('date_joined')
        profile.user = id
        profile.user_type = 'E'

        if commit:
            profile.save()
            emp = Employee(id = Employee.objects.all().count()+1, name = profile.name , address = profile.address)
            emp.save()
            return profile

class SupplierProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = (
            'name',
            'address',

        )

    def save(self,commit=True):
        profile = super(SupplierProfileForm,self).save(commit=False)
        profile.name = self.cleaned_data['name']
        profile.address = self.cleaned_data['address']
        id = User.objects.latest('date_joined')
        profile.user = id
        profile.user_type = 'S'


        if commit:
            profile.save()

            return profile
# class BuyPorscheForm(forms.ModelForm):

#     class Meta:
#         model = Product
#         fields = (
#             'description',
#             'location',
#             'phone_number',
#             'birth_date',

#         )

dbms_app/views.py
import random
from django.shortcuts import render,redirect
from .models import Orderline,Customer,Product,Assembling,Employee,ProductPart,Part,Profile,Supplier
from .forms import RegistrationForm,CustomerProfileForm, EmployeeProfileForm,SupplierProfileForm
from django.urls import reverse
from django.db.models import Max

def home(request):

    if request.user.is_authenticated:
        args = {
            'username':request.user
        }
    else:
        args = {
            'username':' '
        }
    return render(request,'index.html',args)

def emp_register(request):
    if request.method == 'POST':
        userform = RegistrationForm(request.POST)
        profileform = EmployeeProfileForm(request.POST)
        if userform.is_valid() and profileform.is_valid() :
            form1 = userform.save()
            form2 = profileform.save()
            
            return redirect(reverse('dbms_app:login'))
    else:
        userform = RegistrationForm()
        profileform = EmployeeProfileForm()
    args = {'form1':userform, 'form2':profileform}

    return render(request,'dbms_app/reg_form.html',args)

def supp_register(request):
   
    if request.method == 'POST':
        userform = RegistrationForm(request.POST)
        profileform = SupplierProfileForm(request.POST)
        if userform.is_valid() and profileform.is_valid() :
            form1 = userform.save()
            form2 = profileform.save()
            return redirect(reverse('dbms_app:login'))
    else:
        userform = RegistrationForm()
        profileform = SupplierProfileForm()
    args = {'form1':userform, 'form2':profileform}

    return render(request,'dbms_app/reg_form.html',args)

def cust_register(request):
    if request.method == 'POST':
        userform = RegistrationForm(request.POST)
        profileform = CustomerProfileForm(request.POST)
        if userform.is_valid() and profileform.is_valid() :
            form1 = userform.save()
            form2 = profileform.save()
            return redirect(reverse('dbms_app:login'))
    else:
        userform = RegistrationForm()
        profileform = CustomerProfileForm()
    args = {'form1':userform, 'form2':profileform}

    return render(request,'dbms_app/reg_form.html',args)


def buy_porsche(request):

    if request.method == 'POST':
        form = request.POST
        if form:
            profile = Profile.objects.get( user = request.user)
            customer = Customer.objects.get(name = profile.name)
            quantity = form['quantity']
            if Orderline.objects.all().aggregate(Max('id'))['id__max']:
                order_id = Orderline.objects.all().aggregate(Max('id'))['id__max'] +1
            else:
                order_id = 1
            order = Orderline(id = order_id ,customerid = customer, qty = quantity )
            order.save()

            if Product.objects.all().aggregate(Max('id'))['id__max']:
                product_id = Product.objects.all().aggregate(Max('id'))['id__max'] + 1
            else:
                product_id = 1
            porsche_product = Product(id = product_id, orderid = order, title = 'Porsche', price = 10000)
            porsche_product.save()

            empid = random.randint(1,Employee.objects.all().count())
            emp = Employee.objects.get(id = empid)

            assemble = Assembling(productid = porsche_product, employeeid = emp)
            assemble.save()

            for i in range(1,Part.objects.all().count()+1):
                
                pp = ProductPart(productid=porsche_product, partid = Part.objects.get(id=i)) 
                pp.save()
                print(pp)


            return redirect(reverse('dbms_app:success'))

    return render (request,'dbms_app/buy_porsche.html')

def buy_lamborghini(request):

    if request.method == 'POST':
        form = request.POST
        print(request.user)
        if form:
            profile = Profile.objects.get( user = request.user)
            customer = Customer.objects.get(name = profile.name)
            quantity = form['quantity']
            if Orderline.objects.all().aggregate(Max('id'))['id__max']:
                order_id = Orderline.objects.all().aggregate(Max('id'))['id__max'] +1
            else:
                order_id = 1
            order = Orderline(id = order_id ,customerid = customer, qty = quantity )
            order.save()

            if Product.objects.all().aggregate(Max('id'))['id__max']:
                product_id = Product.objects.all().aggregate(Max('id'))['id__max'] + 1
            else:
                product_id = 1
            porsche_product = Product(id = product_id, orderid = order, title = 'Lamborghini', price = 12000 )
            porsche_product.save()

            empid = random.randint(1,Employee.objects.all().count())
            emp = Employee.objects.get(id = empid)

            assemble = Assembling(productid = porsche_product, employeeid = emp)
            assemble.save()

            for i in range(1,Part.objects.all().count()+1):
                pp = ProductPart(productid=porsche_product, partid = Part.objects.get(id=i)) 
                pp.save()


            return redirect(reverse('dbms_app:success'))

    return render (request,'dbms_app/buy_lamborghini.html')

def buy_harley(request):

    if request.method == 'POST':
        form = request.POST
        print(request.user)
        if form:
            profile = Profile.objects.get( user = request.user)
            customer = Customer.objects.get(name = profile.name)
            quantity = form['quantity']
            if Orderline.objects.all().aggregate(Max('id'))['id__max']:
                order_id = Orderline.objects.all().aggregate(Max('id'))['id__max'] +1
            else:
                order_id = 1
            order = Orderline(id = order_id ,customerid = customer, qty = quantity )
            order.save()

            if Product.objects.all().aggregate(Max('id'))['id__max']:
                product_id = Product.objects.all().aggregate(Max('id'))['id__max'] + 1
            else:
                product_id = 1
            porsche_product = Product(id = product_id, orderid = order, title = 'Harley Davidson', price = 8000)
            porsche_product.save()

            empid = random.randint(1,Employee.objects.all().count())
            emp = Employee.objects.get(id = empid)

            assemble = Assembling(productid = porsche_product, employeeid = emp)
            assemble.save()

            for i in range(1,Part.objects.all().count()+1):
                pp = ProductPart(productid=porsche_product, partid = Part.objects.get(id=i)) 
                pp.save()


            return redirect(reverse('dbms_app:success'))

    return render (request,'dbms_app/buy_harley.html')

def buy_royal(request):

    if request.method == 'POST':
        form = request.POST
        print(request.user)
        if form:
            profile = Profile.objects.get( user = request.user)
            customer = Customer.objects.get(name = profile.name)
            quantity = form['quantity']
            if Orderline.objects.all().aggregate(Max('id'))['id__max']:
                order_id = Orderline.objects.all().aggregate(Max('id'))['id__max'] +1
            else:
                order_id = 1
            order = Orderline(id = order_id ,customerid = customer, qty = quantity )
            order.save()

            if Product.objects.all().aggregate(Max('id'))['id__max']:
                product_id = Product.objects.all().aggregate(Max('id'))['id__max'] + 1
            else:
                product_id = 1
            porsche_product = Product(id = product_id, orderid = order, title = 'Royal Enfield', price = 7000)
            porsche_product.save()

            empid = random.randint(1,Employee.objects.all().count())
            emp = Employee.objects.get(id = empid)

            assemble = Assembling(productid = porsche_product, employeeid = emp)
            assemble.save()

            for i in range(1,Part.objects.all().count()+1):
                pp = ProductPart(productid=porsche_product, partid = Part.objects.get(id=i)) 
                pp.save()


            return redirect(reverse('dbms_app:success'))

    return render (request,'dbms_app/buy_royal.html')

def buy_benz(request):

    if request.method == 'POST':
        form = request.POST
        print(request.user)
        if form:
            
            profile = Profile.objects.get( user = request.user)
            customer = Customer.objects.get(name = profile.name)
            quantity = form['quantity']
            if Orderline.objects.all().aggregate(Max('id'))['id__max']:
                order_id = Orderline.objects.all().aggregate(Max('id'))['id__max'] +1
            else:
                order_id = 1
            order = Orderline(id = order_id ,customerid = customer, qty = quantity )
            order.save()

            if Product.objects.all().aggregate(Max('id'))['id__max']:
                product_id = Product.objects.all().aggregate(Max('id'))['id__max'] + 1
            else:
                product_id = 1
            porsche_product = Product(id = product_id, orderid = order, title = 'Mercedes Benz', price = 9000)
            porsche_product.save()

            empid = random.randint(1,Employee.objects.all().count())
            emp = Employee.objects.get(id = empid)

            assemble = Assembling(productid = porsche_product, employeeid = emp)
            assemble.save()

            for i in range(1,Part.objects.all().count()+1):
                pp = ProductPart(productid=porsche_product, partid = Part.objects.get(id=i)) 
                pp.save()


            return redirect(reverse('dbms_app:success'))

    return render (request,'dbms_app/buy_benz.html')

def success(request):

    return render (request,'dbms_app/success.html')

def profile(request):

    if request.user.is_authenticated:
        profile = Profile.objects.get(user = request.user)
        if profile.user_type == 'E':

dbms_app/templates/dbms_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %} {% endblock %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sales and Supply</title>
  </head>
  <body>
    {% block body %} {% endblock %}
  </body>
</html>

dbms_app/templates/dbms_app/buy_benz.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}

<link rel="stylesheet" href="{% static 'css/buy.css' %}" />
<h1>Automobile Details</h1>
    <div class="wrapper">
      <div class="left">
        <img
          src="https://images.pexels.com/photos/3729464/pexels-photo-3729464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
          alt="user"
        />
        <h4>Mercedes Benz</h4>
        <p>Experience the class of Mercedes with 4L-V8 Twin-turbo engine</p>
      </div>
      <div class="right">
        <div class="info">
          <h3>Information</h3>
          <div class="info_data">
            <div class="data">
              <h4>Email</h4>
              <p>kaushik@gmail.com</p>
            </div>
            <div class="data">
              <h4>Phone</h4>
              <p>002-313-998761</p>
            </div>
          </div>
        </div>
<form method="post">
    <!-- <label for="quantity">Quantity</label>
    <input id="quantity" type="text" name="quantity"  /> -->
    {% csrf_token %}
    <!-- <button type="submit" id="login_submit">Buy</button> -->
 

  <div class="buttons">
    <ul class="butns">
      <li>
        <h3>QTY</h3>
        <div class="select">
          <select name="quantity" id="slct">
            <option selected disabled>Choose an option</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>
        </div>
      </li>
      <li>
        <button class="button" type="submit" id="login_submit"><span>Buy </span></button>
      </li>
    </ul>
  </div>
</form>  
</div>
</div>
{% endblock %}

dbms_app/templates/dbms_app/buy_harley.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}

<link rel="stylesheet" href="{% static 'css/buy.css' %}" />
<h1>Automobile Details</h1>
    <div class="wrapper">
      <div class="left">
        <img
          src="https://images.pexels.com/photos/2611686/pexels-photo-2611686.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
          alt="user"
        />
        <h4>Harley Davidson</h4>
        <p>
          Until you've been on a Harley-Davidson, you haven't been on a
          motorcycle
        </p>
      </div>
      <div class="right">
        <div class="info">
          <h3>Information</h3>
          <div class="info_data">
            <div class="data">
              <h4>Email</h4>
              <p>sampath@gmail.com</p>
            </div>
            <div class="data">
              <h4>Phone</h4>
              <p>001-213-998761</p>
            </div>
          </div>
        </div>
<form method="post">
    <!-- <label for="quantity">Quantity</label>
    <input id="quantity" type="text" name="quantity"  /> -->
    {% csrf_token %}
    <!-- <button type="submit" id="login_submit">Buy</button> -->
 

  <div class="buttons">
    <ul class="butns">
      <li>
        <h3>QTY</h3>
        <div class="select">
          <select name="quantity" id="slct">
            <option selected disabled>Choose an option</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>
        </div>
      </li>
      <li>
        <button class="button" type="submit" id="login_submit"><span>Buy </span></button>
      </li>
    </ul>
  </div>
</form>  
</div>
</div>
{% endblock %}

dbms_app/templates/dbms_app/buy_lamborghini.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}

<link rel="stylesheet" href="{% static 'css/buy.css' %}" />
<h1>Automobile Details</h1>
    <div class="wrapper">
      <div class="left">
        <img
          src="https://images.pexels.com/photos/2127733/pexels-photo-2127733.jpeg?cs=srgb&dl=pexels-adrian-dorobantu-2127733.jpg&fm=jpg"
          alt="user"
        />
        <h4>Lamborghini</h4>
        <p>Wander the Trails with its build to last quality</p>
      </div>
      <div class="right">
        <div class="info">
          <h3>Information</h3>
          <div class="info_data">
            <div class="data">
              <h4>Email</h4>
              <p>sumedh@gmail.com</p>
            </div>
            <div class="data">
              <h4>Phone</h4>
              <p>004-513-878761</p>
            </div>
          </div>
        </div>
<form method="post">
    <!-- <label for="quantity">Quantity</label>
    <input id="quantity" type="text" name="quantity"  /> -->
    {% csrf_token %}
    <!-- <button type="submit" id="login_submit">Buy</button> -->
 

  <div class="buttons">
    <ul class="butns">
      <li>
        <h3>QTY</h3>
        <div class="select">
          <select name="quantity" id="slct">
            <option selected disabled>Choose an option</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>
        </div>
      </li>
      <li>
        <button class="button" type="submit" id="login_submit"><span>Buy </span></button>
      </li>
    </ul>
  </div>
</form>  
</div>
</div>
{% endblock %}

dbms_app/templates/dbms_app/buy_porsche.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}

<link rel="stylesheet" href="{% static 'css/buy.css' %}" />
<h1>Automobile Details</h1>
<div class="wrapper">
  <div class="left">
    <img
      src="https://images.hdqwalls.com/download/porsche-911-turbo-s-exclusive-series-2017-sm-1366x768.jpg"
      alt="user"
    />
    <h4>Porsche</h4>
    <p>Their Turbo engines are special for reasons best known to them</p>
  </div>
  <div class="right">
    <div class="info">
      <h3>Information</h3>
      <div class="info_data">
        <div class="data">
          <h4>Email</h4>
          <p>yuva@gmail.com</p>
        </div>
        <div class="data">
          <h4>Phone</h4>
          <p>003-413-898761</p>
        </div>
      </div>
    </div>
<form method="post">
    <!-- <label for="quantity">Quantity</label>
    <input id="quantity" type="text" name="quantity"  /> -->
    {% csrf_token %}
    <!-- <button type="submit" id="login_submit">Buy</button> -->
 

  <div class="buttons">
    <ul class="butns">
      <li>
        <h3>QTY</h3>
        <div class="select">
          <select name="quantity" id="slct">
            <option selected disabled>Choose an option</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>
        </div>
      </li>
      <li>
        <button class="button" type="submit" id="login_submit"><span>Buy </span></button>
      </li>
    </ul>
  </div>
</form>  
</div>
</div>
{% endblock %}

dbms_app/templates/dbms_app/buy_royal.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}

<link rel="stylesheet" href="{% static 'css/buy.css' %}" />
<h1>Automobile Details</h1>
<div class="wrapper">
  <div class="left">
    <img src="https://wallpapercave.com/wp/wp4221540.jpg" alt="user" />
    <h4>Royal Enfield</h4>
    <p>Explore this amazing parallel Twin with madening 47HP</p>
  </div>
  <div class="right">
    <div class="info">
      <h3>Information</h3>
      <div class="info_data">
        <div class="data">
          <h4>Email</h4>
          <p>gautam@gmail.com</p>
        </div>
        <div class="data">
          <h4>Phone</h4>
          <p>005-613-900761</p>
        </div>
      </div>
    </div>
<form method="post">
    <!-- <label for="quantity">Quantity</label>
    <input id="quantity" type="text" name="quantity"  /> -->
    {% csrf_token %}
    <!-- <button type="submit" id="login_submit">Buy</button> -->
 

  <div class="buttons">
    <ul class="butns">
      <li>
        <h3>QTY</h3>
        <div class="select">
          <select name="quantity" id="slct">
            <option selected disabled>Choose an option</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>
        </div>
      </li>
      <li>
        <button class="button" type="submit" id="login_submit"><span>Buy </span></button>
      </li>
    </ul>
  </div>
</form>  
</div>
</div>
{% endblock %}

dbms_app/templates/dbms_app/cust_profile.html
{% extends 'dbms_app/base.html' %} {% load static %} 
{% block head %} 
<link
rel="stylesheet"
type="text/css"
href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
/>
<link rel="stylesheet" href="{% static 'css/cart.css' %}" />

{% endblock %}

{% block body %}



    <div class="container">
      <h1>Your Orders</h1>
      
      <div class="cart">
        
        <div class="products">
            {% for product in products%}
            
          <div class="product">
            {% if product.title == "Mercedes Benz"%}
            <img
              src="https://images.pexels.com/photos/3729464/pexels-photo-3729464.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
              alt=""
            />            
            {% endif %}
            {% if product.title == "Harley Davidson"%}
            <img
              src="https://images.pexels.com/photos/2611686/pexels-photo-2611686.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
              alt=""
            />            
            {% endif %}
            {% if product.title == "Porsche"%}
            <img
              src="https://images.hdqwalls.com/download/porsche-911-turbo-s-exclusive-series-2017-sm-1366x768.jpg"
              alt=""
            />            
            {% endif %}
            {% if product.title == "Royal Enfield"%}
            <img
              src="https://wallpapercave.com/wp/wp4221540.jpg"
              alt=""
            />            
            {% endif %}
            {% if product.title == "Lamborghini"%}
            <img
              src="https://images.pexels.com/photos/2127733/pexels-photo-2127733.jpeg?cs=srgb&dl=pexels-adrian-dorobantu-2127733.jpg&fm=jpg"
              alt=""
            />            
            {% endif %}
            <div class="product-info">
              <h3 class="product-name">{{product.title}}</h3>
              <h4 class="product-price">$ {{product.price}}</h4>
              <h4 class="product-address">{{customer.address}}</h4>
              <p class="product-quantity">Qty : <input value="{{product.orderid.qty}}" name="" /></p>
              <!-- <p class="product-remove">
                <i class="fa fa-trash" aria-hidden="true"></i>
                <span class="remove">Remove</span>
              </p> -->
            </div>
          </div> 
          {% endfor %} 
        </div>     
        
        
        <div class="cart-total">
          <h2>Billing Address</h2>
          <p class="tot-margin">
            <span>Name</span>
            <span>{{customer.name}}</span>
          </p>
          <p>
            <span>Address</span>
            <span>{{customer.address}}</span>
          </p>
          <!-- <a href="#">Proceed to Checkout</a> -->
        </div>
    </div>
    </div>
    
{% endblock%}

dbms_app/templates/dbms_app/emp_profile.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}
<link rel="stylesheet" href="{% static 'css/log.css' %}" />

<div>
    <h1>Automobiles to be assembled</h1>  
    {% for assemble in assembles%}
    <div>
        <p>Name : {{assemble.productid.title}} 
        Customer : {{assemble.productid.orderid.customerid.name}}
    Quantity : {{assemble.productid.orderid.qty}}</p>        
    </div>
   
    {% endfor %}
    <div>
        <h4>Employee Details</h4>
        <p>Name : {{employee.name}} Address : {{employee.address}}</p>
    </div>
</div>
{% endblock%}

dbms_app/templates/dbms_app/login.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}

<link rel="stylesheet" href="{% static 'css/log.css' %}" />

<div class="my_container">
  <div class="center_container">
    <form method="post">
      <h1>Login</h1>
      {% csrf_token %} {{ form.as_p}}
      <button type="submit" id="login_submit">Login</button>
    </form>
    {% if messages %} {% for message in messages %}
    <div class="alert">
      {{message}}
    </div>
    {% endfor %} {% endif %}
  </div>
</div>

{% endblock %}

dbms_app/templates/dbms_app/logout.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}
<link rel="stylesheet" href="{% static 'css/log.css' %}" />
<div class="my_container">
  <div>
    <div class="logout_head">
      <h1>Logged Out</h1>
    </div>
    <div class="logoutwrapper">
      <div class="loghome">
        <p>Go back to home?</p>
        <a href="{%url 'dbms_app:home' %}"><button type="submit" id="login_submit">Home</button></a>
      </div>
      <div class="loglogin">
        <p>Want to login again?</p>
        <a href="{%url 'dbms_app:login' %}"><button type="submit" id="login_submit">Login</button></a>
      </div>
    </div>
  </div>
</div>
{% endblock%}

dbms_app/templates/dbms_app/reg_form.html
{% extends 'dbms_app/base.html' %} {% load static %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/log.css' %}" />
<div class="register_container">

  <form method="post">
    <div class="reg-form">
      <h1>Register</h1>
      {% csrf_token %}
      
      {% for field in form1 %}
      <div class="field">
        <label for="{{ field.id_for_label }}" class="label">{{ field.name }}</label>
        {{ field }}
        
      </div>
      {% endfor %}

      {% for field in form2 %}
      <div class="field">
        <label for="{{ field.id_for_label }}" class="label">{{ field.name }}</label>
        {{ field }}
        
      </div>
      {% endfor %}
      <!-- {{form.as_p}} -->
      <button type="submit" id="login_submit">Submit</button>
    </div>
  </form>
</div>
<script>
  document.getElementsByClassName("label")[0].innerHTML = "Username:"
  document.getElementsByClassName("label")[1].innerHTML = "Password:"
  document.getElementsByClassName("label")[2].innerHTML = "Password Confirmation:"
  document.getElementsByClassName("label")[3].innerHTML = "Name:"
  document.getElementsByClassName("label")[4].innerHTML = "Address:"

</script>
{% endblock %}

dbms_app/templates/dbms_app/success.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}
<link rel="stylesheet" href="{% static 'css/log.css' %}" />
<div class="my_container">
  <div>
    <div class="logout_head">
      <h1>Your Order has been placed</h1>
    </div>
    <div class="logoutwrapper">
      <div class="loghome">
        <p>Go back to home?</p>
        <a href="{% url 'dbms_app:home' %}"><button type="submit" id="login_submit">Home</button></a>
        
      </div>
      <div class="loglogin">
        <p>Check your orders?</p>
        <a href="{% url 'dbms_app:cust_profile' %}"><button type="submit" id="login_submit">Your Orders</button></a>
      </div>
    </div>
  </div>
</div>
{% endblock%}

dbms_app/templates/dbms_app/supp_profile.html
{% extends 'dbms_app/base.html' %} {% load static %} {% block body %}
<link rel="stylesheet" href="{% static 'css/log.css' %}" />
<div>
    <h1>Automobile parts to be Supplier</h1>  
    {% for productpart in productparts%}
    <div>
        <p>Name : {{productpart.partid.name}} 
        Automobile : {{productpart.productid.title}}
    </p>        
    </div>
   
    {% endfor %}
    <div>
        <h4>Supplier Details</h4>
        <p>Name : {{supplier.name}} Address : {{supplier.address}}</p>
    </div>
</div>
{% endblock%}